# Site settings
title: Saurabh Verma
header-img: img/home-bg.jpg
copyright_name: Saurabh Verma
description: "Computer Scientist. Passionate. Fun Loving. Burning with curiosity."
baseurl: ""
url: "https://saurrv.github.io/"
twitter_username: saurv4u
github_username:  saurv4u
facebook_username:  saurrv
email_username:  saurrv@gmail.com
instagram_username:  _saurabhverma_
linkedin_username:  saurabh-verma-iitr
quora_username:  Saurabh-Verma-43

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
